ignore_merge_commits = true

[commit_types]
padd = { changelog_title = "Project Add", omit_from_changelog = true }
pupdate = { changelog_title = "Project Update", omit_from_changelog = true }
premove = { changelog_title = "Project Remove", omit_from_changelog = true }
ci = {} # disabled
revert = {} # disabled
docs = {} # disabled
perf = {} # disabled
