# Configuration for the website

base_url = "https://lucasguesserts.github.io"
title = "/home/lucasguesser"
description = "Lucas Guesser's personal website"
author = "Lucas Guesser"

theme = "tabi"

build_search_index = true

compile_sass = true
generate_sitemap = false
generate_robots_txt = true

default_language = "en"

[languages.pt]
title = "/home/lucasguesser"
description = "Website pessoal de Lucas Guesser"
build_search_index = true

[markdown]
bottom_footnotes = true
external_links_class = "external"

[extra]
show_selected_language_code_in_language_switcher = true

use_cdn = true
comment = false
iine = false

# See https://welpo.github.io/tabi/blog/mastering-tabi-settings/#social-media-cards
# Path to the fallback image for social media cards (the preview image shown when sharing a link on WhatsApp, LinkedIn…).
# Can be set at page or section levels, following the hierarchy: page > section > config. See: https://github.com/welpo/tabi/pull/128
# TODO: automate link preview image generation with https://osc.garden/blog/automating-social-media-cards-zola/
social_media_card = "images/profile-picture.jpg"

# display both the created and the updated dates
post_listing_date = "updated"

# Projects
projects_path = "projects/_index.md"

# the color theme
skin = "blue"

# Website source code
remote_repository_url = "https://github.com/lucasguesserts/lucasguesserts.github.io"
remote_repository_git_platform = "auto"
remote_repository_branch = "main"
show_remote_changes = false
show_remote_source = false

# ===============================
# Navigation
# https://welpo.github.io/tabi/blog/mastering-tabi-settings/#navigation
# ===============================
menu = [
    { name = "home", url = "/", trailing_slash = false },
    { name = "blog", url = "blog", trailing_slash = true },
    { name = "projects", url = "projects", trailing_slash = true },
    { name = "about", url = "about", trailing_slash = true },
]
quick_navigation_buttons = true
toc = true
show_previous_next_article_links = false
invert_previous_next_article_links = false

# ===============================
# Usability
# https://welpo.github.io/tabi/blog/mastering-tabi-settings/#usability
# ===============================
copy_button = true
code_block_name_links = true
katex = true
mermaid = true

# ===============================
# Footer
# https://welpo.github.io/tabi/blog/mastering-tabi-settings/#footer
# ===============================
socials = [
    { name = "github", url = "https://github.com/lucasguesserts/", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/lucasguesserts/", icon = "linkedin" },
]
footer_menu = [
    # { url = "about", name = "about", trailing_slash = true },
    # { url = "privacy", name = "privacy", trailing_slash = true },
    # { url = "sitemap.xml", name = "Sitemap", trailing_slash = false },
    # { url = "https://example.com", name = "external link", trailing_slash = true },
]
copyright = "© $CURRENT_YEAR $AUTHOR $SEPARATOR [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) license."
copyright_translations.pt = "© $CURRENT_YEAR $AUTHOR $SEPARATOR [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."

# ===============================
# Metadata
# https://welpo.github.io/tabi/blog/mastering-tabi-settings/#metadata
# ===============================
show_author = false
show_reading_time = false
show_date = false

